services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env
    environment:
      TZ: ${TZ}
    ports:
      - "8000:8000"     # 디버깅용
    expose:
      - "8000"
    # SQLite 임시 사용 시 데이터 유지용(선택)
    volumes:
      - api_data:/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      TZ: ${TZ}
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly no
    ports:
      - "6379:6379"
    restart: unless-stopped
    profiles: ["dev"]

volumes:
  api_data:
